AspNetCore/ChushkaWebApp/ChushkaWebApp/Controllers/AccountsController.cs
namespace ChushkaWebApp.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Linq;
    using ChushkaWebApp.Models;
    using ViewModels.Accounts;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Authorization;

    public class AccountsController : Controller
    {
        private SignInManager<ChushkaUser> signInManager;

        public AccountsController(SignInManager<ChushkaUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public IActionResult Login()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            var user = this.signInManager.UserManager.Users.FirstOrDefault(u => u.UserName == model.Username);
            try
            {
                this.signInManager.SignInAsync(user, false).Wait();
            }
            catch (Exception)
            {
                return this.View(model);
            }

            return this.RedirectToAction("Index", "Home");
        }

        public IActionResult Register()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = new ChushkaUser()
            {
                Email = model.Email,
                FullName = model.FullName,
                UserName = model.Username
            };

            var result = this.signInManager.UserManager.CreateAsync(user, model.Password).Result;

            if (this.signInManager.UserManager.Users.Count() == 1)
            {
                var roleResult = this.signInManager.UserManager.AddToRoleAsync(user, "Administrator").Result;
                if (roleResult.Errors.Any())
                {
                    return this.View();
                }
            }

            if (result.Succeeded)
            {
                return this.RedirectToAction("Login");
            }

            return View();
        }

        [Authorize]
        public IActionResult Logout()
        {
            this.signInManager.SignOutAsync().Wait();
            return this.RedirectToAction("Index", "Home");
        }
    }
}

AspNetCore/ChushkaWebApp/ChushkaWebApp/Controllers/OrdersController.cs
namespace ChushkaWebApp.Web.Controllers
{
    using System.Linq;
    using Services.Interfaces;
    using ViewModels.Orders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class OrdersController : Controller
    {
        private readonly IOrderService orders;

        public OrdersController(IOrderService orders)
        {
            this.orders = orders;
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult All()
        {
            var allOrdersViewModel = new AllOrdersViewModel
            {
                Orders = this.orders.All().Select(o => new OrderViewModel
                {
                    Id = o.Id,
                    Customer = o.Customer,
                    Product = o.Product,
                    OrderedOn = o.OrderedOn
                })
            };

            return this.View(allOrdersViewModel);
        }
    }
}

AspNetCore/ChushkaWebApp/ChushkaWebApp/Controllers/ProductsController.cs
namespace ChushkaWebApp.Web.Controllers
{
    using ChushkaWebApp.Models;
    using ChushkaWebApp.Models.Enums;
    using ViewModels.Products;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Identity;
    using Services.Interfaces;
    using System;

    public class ProductsController : Controller
    {
        private readonly IProductService products;
        private readonly IOrderService orders;
        private UserManager<ChushkaUser> users;

        public ProductsController(IProductService products, IOrderService orders, UserManager<ChushkaUser> users)
        {
            this.products = products;
            this.orders = orders;
            this.users = users;
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            if (!this.products.Exists(id))
            {
                return this.NotFound();
            }

            var product = this.products.FindById(id);

            var productDetailsViewModel = new ProductDetailsViewModel
            {
                Id = product.Id,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                Type = product.Type
            };

            return this.View(productDetailsViewModel);
        }

        [Authorize]
        public IActionResult Order(int id)
        {
            if (!this.products.Exists(id))
            {
                return this.NotFound();
            }

            var user = this.users.FindByNameAsync(this.User.Identity.Name).Result;
            this.orders.Create(user.Id, id);

            return this.RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(CreateProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            if (!Enum.TryParse(model.Type, true, out ProductType type))
            {
                return this.View(model);
            }

            var productId = this.products.Create(model.Name, model.Price, model.Description, type);

            return this.RedirectToAction("Details", new { id = productId });
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int id)
        {
            if (!this.products.Exists(id))
            {
                return this.NotFound();
            }

            var product = this.products.FindById(id);

            var productUpdateViewModel = new UpdateProductViewModel
            {
                Id = product.Id,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                Type = product.Type.ToString()
            };

            return this.View(productUpdateViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(UpdateProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            if (!this.products.Exists(model.Id))
            {
                return this.NotFound();
            }

            if (!Enum.TryParse(model.Type, true, out ProductType type))
            {
                return this.View(model);
            }

            this.products.Edit(model.Id, model.Name, model.Price, model.Description, type);

            return this.RedirectToAction("Details", new { id = model.Id });
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int id)
        {
            if (!this.products.Exists(id))
            {
                return this.NotFound();
            }

            var product = this.products.FindById(id);

            var productUpdateViewModel = new UpdateProductViewModel
            {
                Id = product.Id,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                Type = product.Type.ToString()
            };

            return this.View(productUpdateViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(UpdateProductViewModel model)
        {
            if (!this.products.Exists(model.Id))
            {
                return this.NotFound();
            }

            this.products.Delete(model.Id);

            return this.RedirectToAction("Index", "Home");
        }
    }
}

AspNetCore/ChushkaWebApp/ChushkaWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>CHUSHKA</title>
    <link rel="stylesheet" type="text/css" href="/css/reset-css.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body>
    <div class="container-fluid">
        <header>
            <nav class="navbar navbar-expand-lg chushka-bg-color">
                <a class="navbar-brand" href="/">CHUSHKA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Accounts" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Accounts" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Products" asp-action="Create">Create Product</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Orders" asp-action="All">All Orders</a>
                                </li>
                            }                      
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Accounts" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    }
                </div>
            </nav>
        </header>
        <main class="mt-3">
            @RenderBody()
        </main>
        <footer>
            <div class="container-fluid chushka-bg-color">
                <div class="text-white p-2 text-center">
                    &copy; CopyRight Sanity Web Design Studios 2018. All rights reserved.
                </div>
            </div>
        </footer>
    </div>
</body>
</html>